name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  checkout-setup:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
      - name: Run Flutter doctor
        run: flutter doctor -v

  code-quality:
    runs-on: ubuntu-latest
    needs: checkout-setup
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
      - name: Install dependencies
        run: flutter pub get
      - name: Run Flutter analyze
        run: flutter analyze
      - name: Run unit tests
        run: flutter test

  build-android:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
      - name: Install dependencies
        run: flutter pub get
      - name: Build Android APK
        run: flutter build apk --release
      - name: Build Android AAB
        run: flutter build appbundle --release
      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
      - name: Upload Android AAB artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-aab
          path: build/app/outputs/bundle/release/app-release.aab

  build-ios:
    runs-on: macos-latest
    needs: code-quality
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS IPA
        run: flutter build ios --release --no-codesign
      - name: Upload iOS IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: ios-ipa
          path: build/ios/iphoneos/Runner.ipa

  deploy:
    needs: build-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy Android to Firebase
        run: |
          curl -sL https://firebase.tools | bash
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app ${{ secrets.FIREBASE_APP_ID }} --groups "testers" --token ${{ secrets.FIREBASE_AUTH_TOKEN }}
      - name: Deploy to Google Play Store (Fastlane)
        run: |
          gem install fastlane
          fastlane android beta --json_key ${{ secrets.FASTLANE_ANDROID_JSON_KEY }}
      - name: Deploy to Apple App Store (Fastlane)
        run: |
          gem install fastlane
          fastlane ios beta --username ${{ secrets.FASTLANE_APPLE_USERNAME }} --app_identifier ${{ secrets.FASTLANE_APPLE_CERT }} --password ${{ secrets.FASTLANE_APPLE_PASSWORD }}

