name: Flutter CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '* * * * *'  # Run every minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2

      # 2. Set up Flutter SDK with a specific version
      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'  # Specify a stable version (change to the latest stable)

      # 3. Code Quality Checks
      - name: Flutter Analyze (Linting)
        run: flutter analyze

      - name: Flutter Test (Unit Tests)
        run: flutter test



